app/models.py
from datetime import datetime

from sqlalchemy.orm import validates

from app import db


class Repo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    path = db.Column(db.String(4096), nullable=False)
    status = db.Column(db.Text, nullable=True)
    updated = db.Column(db.DateTime, nullable=True)

    @validates('path')
    def validate_path(self, key, value):
        if not value or not value.strip():
            raise ValueError('path cannot be empty')
        return value

    def update_status(self, status):
        self.status = status
        self.updated = datetime.now()

    @classmethod
    def repo_exists(cls, path):
        return Repo.query.filter_by(path=path).count() > 0

app/main/forms.py
from pathlib import Path

from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, DataRequired, ValidationError


class AddReposForm(FlaskForm):
    basepath = StringField("Base Path", validators=[
        InputRequired("Base Path is required"),
        DataRequired("Base Path cannot be empty")
    ])

    def validate_basepath(form, field):
        path = Path(field.data).expanduser()
        if not path.exists():
            raise ValidationError("Base Path does not exist")

        if not path.is_dir():
            raise ValidationError("Base Path is not a directory")


class FilterReposForm(FlaskForm):
    filter = StringField("Filter")

app/__init__.py
import os

from flask import Flask

import config
from app.extensions import db # noqa
from app.extensions import init_extensions


basedir = os.path.abspath(os.path.dirname(__file__))
env_flask_env = os.environ.get("FLASK_ENV")


def create_app(flask_env=env_flask_env):
    app = Flask(__name__)
    app.config.from_object(config.from_flask_env(flask_env))

    init_extensions(app)

    from app.main.views import main
    app.register_blueprint(main)

    return app

app/main/views.py
import os.path
from datetime import datetime

from flask import render_template, Blueprint, request, redirect, url_for, flash, abort

import app.git

from app import db
from app.models import Repo
from app.main.forms import AddReposForm, FilterReposForm
from app.main.services import search_and_add_git_repos_from_base_path


main = Blueprint("main", __name__)


@main.route("/")
def home():
    repos = Repo.query.order_by(Repo.path).all()
    total_count = len(repos)
    form = FilterReposForm(request.args, meta=dict(csrf=False))

    if form.filter.data:
        filter = form.filter.data.lower()
        repos = [repo for repo in repos if filter in repo.path.lower()]

    return render_template('home.html', repos=repos, total_count=total_count, form=form)


@main.route('/repos/<int:repo_id>/refresh')
def refreshrepo(repo_id):
    repo = Repo.query.filter_by(id=repo_id).first()
    if not repo:
        return abort(404)

    git_repo = app.git.repo_from_path(repo.path)
    status = git_repo.get_status() if git_repo else 'Not a git repo!'

    repo.update_status(status)
    db.session.add(repo)
    db.session.commit()

    return redirect(url_for('main.home'))


@main.route('/repos/<int:repo_id>/delete', methods=['POST'])
def deleterepo(repo_id):
    repo = Repo.query.filter_by(id=repo_id).first()
    if repo:
        db.session.delete(repo)
        db.session.commit()

        flash(f'Deleted: { repo.path }', 'success')

    return redirect(url_for('main.home'))


@main.route('/repos', methods=['GET', 'POST'])
def addrepos():
    form = AddReposForm()

    if form.validate_on_submit():
        new_repos = search_and_add_git_repos_from_base_path(form.basepath.data)
        number_added = len(new_repos)

        if number_added == 0:
            flash('No new repos were found', 'warning')
        else:
            parts = [f'{number_added} repos added:', '<ul>']

            for new_repo in new_repos:
                parts.append(f'<li>{new_repo}</li>')

            parts.append('</ul>')

            flash('\n'.join(parts), 'success')

        return redirect(url_for('main.home'))

    if form.errors:
        for _, errors in form.errors.items():
            for error in errors:
                flash(f'{error}', 'error')

    return render_template('addrepos.html', form=form)


@main.app_template_filter()
def path_parent(path_string):
    return os.path.dirname(path_string) + os.path.sep


@main.app_template_filter()
def path_last(path_string):
    return os.path.basename(path_string)


@main.app_template_filter()
def last_updated(timestamp):
    diff = (datetime.now() - timestamp).total_seconds()

    if diff < 10:
        return 'a few seconds ago'

    if diff < 60 * 1.5:
        return 'about a minute ago'

    if diff < 5 * 60:
        return 'a few minutes ago'

    if diff < 58 * 60:
        return f'about {int(diff) // 60} minutes ago'

    if diff < 65 * 60:
        return 'about an hour ago'

    if diff < 24 * 60 * 60:
        return f'about {int(diff) // (60 * 60)} hours ago'

    if diff < 24 * 1.2 * 60 * 60:
        return 'about a day ago'

    return 'more than a day ago'

app/templates/addrepos.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 mt-3">
    <form method="POST">
        <div class="mb-3">
            {{ form.hidden_tag() }}
            {{ form.basepath.label(class_="form-label") }}
            {{ form.basepath(class_="form-control") }}
            <div class="form-text">
                Find and add git repos contained within this base path.
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Find & Add</button>
    </form>
</div>

{% endblock %}

app/templates/base.html
{% import 'macros.html' as macros %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Git Dashboard v0.1</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-icons.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <div class="container">

            <h1><a href="{{ url_for('main.home') }}">Git Dashboard</a></h1>

            {{ macros.alerts() }}

            {% block content %}
            {% endblock %}
        </div>

        <script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}" async defer></script>
        <script src="{{ url_for('static', filename='app.js') }}" async defer></script>
    </body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<form action="{{ url_for('main.addrepos') }}" class="mt-3">
    <button type="submit" class="btn btn-outline-primary">Add Repos</button>
</form>

<div class="col-md-6">
    <form method="GET" class="mt-3 mb-3">
        <div class="input-group input-group-sm">
            {{ form.filter(class_="form-control", placeholder="Filter displayed repos by string (match is done by contains string)") }}
            <button type="submit" class="btn btn-outline-secondary">Filter</button>
        </div>
    </form>
</div>

{% if total_count > 0 %}

{% if repos %}
<ul class="col-md-6 list-group">
    {% for repo in repos %}
    <div class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h5><span class="fw-lighter">{{ repo.path|path_parent }}</span>{{ repo.path|path_last }}</h5>

            <div class="d-flex">
            <form action="{{ url_for('main.deleterepo', repo_id=repo.id) }}" method="POST">
                <button type="submit" class="btn p-0"><i class="bi bi-trash"></i></button>
            </form>
            <form action="{{ url_for('main.refreshrepo', repo_id=repo.id) }}" method="GET">
                <button type="submit" class="btn p-0"><i class="bi bi-arrow-clockwise"></i></button>
            </form>
            </div>
        </div>
        {% if repo.updated %}
            <small class="text-muted">Last updated: {{ repo.updated|last_updated }}</small>
            <pre class="repo-status text-muted mt-1">{{ repo.status }}</pre>
        {% else %}
            <small class="text-muted">Last updated: <span class="fst-italic">never</span></small>
        {% endif %}
    </div>
    {% endfor %}
</ul>
{% elif form.filter.data %}
<div class="alert alert-info">
No repos matched the filter
</div>
{% endif %}

{% else %}
<div class="alert alert-info">
You have no repos
</div>
{% endif %}


{% endblock %}

app/templates/macros.html
{% macro category_alerts(messages, desired_category, alert_type) %}
    {% for category, message in messages %}
        {% if category == desired_category %}
            <div class="alert alert-{{alert_type}}">
                {{ message|safe }}
            </div>
        {% endif %}
    {% endfor %}
{% endmacro %}

{% macro error_alerts(messages) %}
    {{ category_alerts(messages, 'error', 'danger') }}
{% endmacro %}

{% macro warning_alerts(messages) %}
    {{ category_alerts(messages, 'warning', 'warning') }}
{% endmacro %}

{% macro info_alerts(messages) %}
    {{ category_alerts(messages, 'success', 'success') }}
{% endmacro %}

{% macro alerts() %}
    {% with messages = get_flashed_messages(with_categories=True)  %}
        {% if messages %}
            {{ error_alerts(messages) }}
            {{ warning_alerts(messages) }}
            {{ info_alerts(messages) }}
        {% endif %}
    {% endwith %}
{% endmacro %}